Traceback (most recent call last):
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\dudas\anaconda3\envs\wintest\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\dudas\anaconda3\envs\wintest\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%R
library(installr)
install.packages.zip("https://cran.r-project.org/bin/windows/contrib/4.2/ggplot2_3.3.3.zip")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mRRuntimeError[0m                             Traceback (most recent call last)
[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\ipython\rmagic.py[0m in [0;36meval[1;34m(self, code)[0m
[0;32m    267[0m                 [1;31m# Need the newline in case the last line in code is a comment.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 268[1;33m                 [0mvalue[0m[1;33m,[0m [0mvisible[0m [1;33m=[0m [0mro[0m[1;33m.[0m[0mr[0m[1;33m([0m[1;34m"withVisible({%s\n})"[0m [1;33m%[0m [0mcode[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    269[0m             [1;32mexcept[0m [1;33m([0m[0mri[0m[1;33m.[0m[0membedded[0m[1;33m.[0m[0mRRuntimeError[0m[1;33m,[0m [0mValueError[0m[1;33m)[0m [1;32mas[0m [0mexception[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\robjects\__init__.py[0m in [0;36m__call__[1;34m(self, string)[0m
[0;32m    437[0m         [0mp[0m [1;33m=[0m [0mrinterface[0m[1;33m.[0m[0mparse[0m[1;33m([0m[0mstring[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 438[1;33m         [0mres[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0meval[0m[1;33m([0m[0mp[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    439[0m         [1;32mreturn[0m [0mconversion[0m[1;33m.[0m[0mrpy2py[0m[1;33m([0m[0mres[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\robjects\functions.py[0m in [0;36m__call__[1;34m(self, *args, **kwargs)[0m
[0;32m    198[0m         return (super(SignatureTranslatedFunction, self)
[1;32m--> 199[1;33m                 .__call__(*args, **kwargs))
[0m[0;32m    200[0m [1;33m[0m[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\robjects\functions.py[0m in [0;36m__call__[1;34m(self, *args, **kwargs)[0m
[0;32m    124[0m                 [0mnew_kwargs[0m[1;33m[[0m[0mk[0m[1;33m][0m [1;33m=[0m [0mconversion[0m[1;33m.[0m[0mpy2rpy[0m[1;33m([0m[0mv[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 125[1;33m         [0mres[0m [1;33m=[0m [0msuper[0m[1;33m([0m[0mFunction[0m[1;33m,[0m [0mself[0m[1;33m)[0m[1;33m.[0m[0m__call__[0m[1;33m([0m[1;33m*[0m[0mnew_args[0m[1;33m,[0m [1;33m**[0m[0mnew_kwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    126[0m         [0mres[0m [1;33m=[0m [0mconversion[0m[1;33m.[0m[0mrpy2py[0m[1;33m([0m[0mres[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\rinterface_lib\conversion.py[0m in [0;36m_[1;34m(*args, **kwargs)[0m
[0;32m     44[0m     [1;32mdef[0m [0m_[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 45[1;33m         [0mcdata[0m [1;33m=[0m [0mfunction[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     46[0m         [1;31m# TODO: test cdata is of the expected CType[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\rinterface.py[0m in [0;36m__call__[1;34m(self, *args, **kwargs)[0m
[0;32m    679[0m             [1;32mif[0m [0merror_occured[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 680[1;33m                 [1;32mraise[0m [0membedded[0m[1;33m.[0m[0mRRuntimeError[0m[1;33m([0m[0m_rinterface[0m[1;33m.[0m[0m_geterrmessage[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    681[0m         [1;32mreturn[0m [0mres[0m[1;33m[0m[1;33m[0m[0m

[1;31mRRuntimeError[0m: Error in library(installr) : there is no package called 'installr'


During handling of the above exception, another exception occurred:

[1;31mRInterpreterError[0m                         Traceback (most recent call last)
[1;32m<ipython-input-3-ff8ccd2a6304>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mget_ipython[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0mrun_cell_magic[0m[1;33m([0m[1;34m'R'[0m[1;33m,[0m [1;34m''[0m[1;33m,[0m [1;34m'library(installr)\ninstall.packages.zip("https://cran.r-project.org/bin/windows/contrib/4.2/ggplot2_3.3.3.zip")\n'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\IPython\core\interactiveshell.py[0m in [0;36mrun_cell_magic[1;34m(self, magic_name, line, cell)[0m
[0;32m   2401[0m             [1;32mwith[0m [0mself[0m[1;33m.[0m[0mbuiltin_trap[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2402[0m                 [0margs[0m [1;33m=[0m [1;33m([0m[0mmagic_arg_s[0m[1;33m,[0m [0mcell[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2403[1;33m                 [0mresult[0m [1;33m=[0m [0mfn[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   2404[0m             [1;32mreturn[0m [0mresult[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2405[0m [1;33m[0m[0m

[1;32m<decorator-gen-122>[0m in [0;36mR[1;34m(self, line, cell, local_ns)[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\IPython\core\magic.py[0m in [0;36m<lambda>[1;34m(f, *a, **k)[0m
[0;32m    185[0m     [1;31m# but it's overkill for just that one bit of state.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m    186[0m     [1;32mdef[0m [0mmagic_deco[0m[1;33m([0m[0marg[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 187[1;33m         [0mcall[0m [1;33m=[0m [1;32mlambda[0m [0mf[0m[1;33m,[0m [1;33m*[0m[0ma[0m[1;33m,[0m [1;33m**[0m[0mk[0m[1;33m:[0m [0mf[0m[1;33m([0m[1;33m*[0m[0ma[0m[1;33m,[0m [1;33m**[0m[0mk[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    188[0m [1;33m[0m[0m
[0;32m    189[0m         [1;32mif[0m [0mcallable[0m[1;33m([0m[0marg[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\ipython\rmagic.py[0m in [0;36mR[1;34m(self, line, cell, local_ns)[0m
[0;32m    781[0m             [1;32mif[0m [1;32mnot[0m [0me[0m[1;33m.[0m[0mstdout[0m[1;33m.[0m[0mendswith[0m[1;33m([0m[0me[0m[1;33m.[0m[0merr[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    782[0m                 [0mprint[0m[1;33m([0m[0me[0m[1;33m.[0m[0merr[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 783[1;33m             [1;32mraise[0m [0me[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    784[0m         [1;32mfinally[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    785[0m             [1;32mif[0m [0mself[0m[1;33m.[0m[0mdevice[0m [1;32min[0m [1;33m[[0m[1;34m'png'[0m[1;33m,[0m [1;34m'svg'[0m[1;33m][0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\ipython\rmagic.py[0m in [0;36mR[1;34m(self, line, cell, local_ns)[0m
[0;32m    761[0m                     [0mreturn_output[0m [1;33m=[0m [1;32mFalse[0m[1;33m[0m[1;33m[0m[0m
[0;32m    762[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 763[1;33m                 [0mtext_result[0m[1;33m,[0m [0mresult[0m[1;33m,[0m [0mvisible[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0meval[0m[1;33m([0m[0mcode[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    764[0m                 [0mtext_output[0m [1;33m+=[0m [0mtext_result[0m[1;33m[0m[1;33m[0m[0m
[0;32m    765[0m                 [1;32mif[0m [0mvisible[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\dudas\anaconda3\envs\wintest\lib\site-packages\rpy2\ipython\rmagic.py[0m in [0;36meval[1;34m(self, code)[0m
[0;32m    271[0m                 [0mwarning_or_other_msg[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mflush[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    272[0m                 raise RInterpreterError(code, str(exception),
[1;32m--> 273[1;33m                                         warning_or_other_msg)
[0m[0;32m    274[0m             [0mtext_output[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mflush[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    275[0m             [1;32mreturn[0m [0mtext_output[0m[1;33m,[0m [0mvalue[0m[1;33m,[0m [0mvisible[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m

[1;31mRInterpreterError[0m: Failed to parse and evaluate line 'library(installr)\ninstall.packages.zip("https://cran.r-project.org/bin/windows/contrib/4.2/ggplot2_3.3.3.zip")\n'.
R error message: "Error in library(installr) : there is no package called 'installr'"
RInterpreterError: Failed to parse and evaluate line 'library(installr)\ninstall.packages.zip("https://cran.r-project.org/bin/windows/contrib/4.2/ggplot2_3.3.3.zip")\n'.
R error message: "Error in library(installr) : there is no package called 'installr'"

